### ISSUE TITLE
Motion to schedule interface and storyboarding design meeting

### ISSUE THREAD

**Issue by op23n1** [CMPUT301F21T13/FungalFunhouse#2]
Meeting will cover general design philosophy and concepts as well as how this will be documented and layed out.

### Current suggested time:
Saturday October 9th, 13:00 MST

Are there any objections or concerns for this planned time?

Additionally is there any additional subject matter that should be discussed?

**Comment by jakobrichert** [comment]
Yeah I can be there for 13:00! I'm going to try and come up with a draft for the interface before we meet.

**Comment by jakobrichert** [comment]
https://drive.google.com/file/d/1QXllD-ckdxsHGRQRFqPeThDAPdMzdkRs/view?usp=sharing here's a link for a possible UML drawing web application we can use.
