### ISSUE TITLE
Draft UI-prototype and mockup storyboard sequences for general UI flow

### ISSUE THREAD

**Issue by op23n1** [CMPUT301F21T13/FungalFunhouse#5]
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, diagram storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements.

**Comment by Genna-C** [comment]
Began prototyping through LucidChart, involving basic home and profile screens

**Comment by op23n1** [comment]
Finalized activity transition flow, and designed legend.
