### ISSUE TITLE
2021/10/14 13:00-14:00 General Meeting for Catch-up and Storyboard Design

### ISSUE THREAD

**Issue by Genna-C** [CMPUT301F21T13/FungalFunhouse#8]
General Meeting in Discord on Thursday, October 14th 2021 
Meant for keeping everyone up to date, and focusing on storyboard finalization (specificity!)

**Comment by FunnyBot9980** [comment]
Group members attending: jmacdona, genna, storch

**Comment by Genna-C** [comment]
Tasks completed in the meeting: Updating storyboard draft to include adding, editing and deleting both habits and habit events, added user stories, and updated minor details and specifications for interface. 
Members attended: jmacdona, genna, storch
