### ISSUE TITLE
Research Database implementation solutions

### ISSUE THREAD

**Issue by op23n1** [CMPUT301F21T13/FungalFunhouse#9]
* Figure out solutions for local databases on android and then research synchronicity between a local database for offline use and Firestore for data backup.
* Report to this issue with specific technologies / necessary libraries for implementation

**Comment by GTorchy** [comment]
After a little bit of looking, I've found how to store data locally using app-specific storage. This link: [https://developer.android.com/training/data-storage](url) shows the android data and file storage overview. Using app-specific storage so we can have our own file hierarchy in combination with SQLite could be a possible solution.

As for priorities, I think the local database should be used to automatically update the Firestore on **closing** (or possibly in real-time as any edit is made) of the app to ensure any edits made are sent to Firestore. If we were to have the user manually choose when to update the Firestore its possible that they don't update it for a long time causing possible issues when it is finally updated.
